version: '2'
services:
  integracao-helios:
    image: sistemapmmg/integracao-helios:latest
    container_name: integracao-helios
    environment:
      - FTP_URL=ftp-server
      - FTP_USER=cameradts
      - FTP_PASSWD=cameradts
      - HELIOS_URI=https://helios.policiamilitar.mg.gov.br/v3/api/_track/register
      - TOKEN_FORNECEDOR=token_fornecedor
    restart: always
    entrypoint: bash -c "php ./run.php"
  ftpd-server:
    image: fauria/vsftpd
    container_name: ftp-server
    environment:
      - FTP_USER=cameradts
      - FTP_PASS=cameradts
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
      - PASV_ENABLE=YES
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - ./ftp-files:/home/vsftpd
    restart: always
    
